[package]
name = "tuix"
description = "Cross-platform GUI toolkit"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["ui", "gui", "gpu", "graphics", "css"]
repository = "https://github.com/geom3trik/tuix"
edition = "2018"


[dependencies]
gl = "0.14.0"
glutin = "0.24.1"
baseview = {git = "https://github.com/RustAudio/baseview"}
cssparser = "0.27.2"
femtovg = "0.1.0"
image = "0.23.12"
rtrb = "0.1.1"
raw-gl-context = {git = "https://github.com/glowcoil/raw-gl-context"}