[package]
name = "tuix"
version = "0.1.0"
authors = ["George Atkinson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.24.1"
cssparser = "0.27.2"
femtovg = "*"
image = "*"