[package]
name = "tuix"
description = "Cross-platform GUI toolkit"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["ui", "gui", "gpu", "graphics", "css"]
repository = "https://github.com/geom3trik/tuix"
edition = "2018"


[dependencies]
gl = "0.14.0"
glutin = "0.26"
cssparser = "0.27.2"
femtovg = {git = "https://github.com/geom3trik/femtovg", branch = "text_fix"}
image = "0.23.12"
bimap = "0.5.3"